Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/computo/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/computo/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/computo/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 168, in wrapped
    return loop.run_until_complete(inner)
  File "/usr/share/miniconda3/envs/computo/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/computo/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/computo/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/computo/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
beta_X1 = b_ginibre_1[['S1', 'P1', 'R1']].values
beta_y1 = b_ginibre_1['process'].values
beta_X1_train, beta_X1_test, beta_y1_train, beta_y1_test = train_test_split(beta_X1, beta_y1, test_size=0.3, shuffle=True, random_state=7)

beta_LR1 = make_pipeline(StandardScaler(), LogisticRegression())
beta_LR1.fit(beta_X1_train, beta_y1_train)
model_Evaluate(beta_LR1, beta_X1_test, beta_y1_test)
------------------

----- stdout -----
              precision    recall  f1-score   support

           0       0.62      0.59      0.60       728
           1       0.63      0.66      0.64       772

    accuracy                           0.62      1500
   macro avg       0.62      0.62      0.62      1500
weighted avg       0.62      0.62      0.62      1500
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
Cell [0;32mIn[8], line 7[0m
[1;32m      5[0m beta_LR1 [38;5;241m=[39m make_pipeline(StandardScaler(), LogisticRegression())
[1;32m      6[0m beta_LR1[38;5;241m.[39mfit(beta_X1_train, beta_y1_train)
[0;32m----> 7[0m [43mmodel_Evaluate[49m[43m([49m[43mbeta_LR1[49m[43m,[49m[43m [49m[43mbeta_X1_test[49m[43m,[49m[43m [49m[43mbeta_y1_test[49m[43m)[49m

Cell [0;32mIn[7], line 31[0m, in [0;36mmodel_Evaluate[0;34m(model, x_tt, y_tt)[0m
[1;32m     29[0m sns[38;5;241m.[39mheatmap(cf_matrix, annot [38;5;241m=[39m labels, cmap [38;5;241m=[39m [38;5;124m'[39m[38;5;124mBlues[39m[38;5;124m'[39m,fmt [38;5;241m=[39m [38;5;124m'[39m[38;5;124m'[39m, xticklabels [38;5;241m=[39m categories, yticklabels [38;5;241m=[39m categories)
[1;32m     30[0m ax[38;5;241m.[39mset_title([38;5;124m"[39m[38;5;124mConfusion Matrix[39m[38;5;124m"[39m, fontdict [38;5;241m=[39m font)
[0;32m---> 31[0m [43max[49m[38;5;241;43m.[39;49m[43mset[49m[43m([49m[43mxlabel[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mPredicted values[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mylabel[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mActual values[39;49m[38;5;124;43m'[39;49m[43m,[49m[43m [49m[43mfontdict[49m[43m [49m[38;5;241;43m=[39;49m[43m [49m[43mfont[49m[43m)[49m
[1;32m     33[0m [38;5;66;03m# Adds subplot on position 2[39;00m
[1;32m     34[0m ax [38;5;241m=[39m fig[38;5;241m.[39madd_subplot([38;5;241m122[39m)

File [0;32m/usr/share/miniconda3/envs/computo/lib/python3.9/site-packages/matplotlib/artist.py:147[0m, in [0;36mArtist.__init_subclass__.<locals>.<lambda>[0;34m(self, **kwargs)[0m
[1;32m    139[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mhasattr[39m([38;5;28mcls[39m[38;5;241m.[39mset, [38;5;124m'[39m[38;5;124m_autogenerated_signature[39m[38;5;124m'[39m):
[1;32m    140[0m     [38;5;66;03m# Don't overwrite cls.set if the subclass or one of its parents[39;00m
[1;32m    141[0m     [38;5;66;03m# has defined a set method set itself.[39;00m
[1;32m    142[0m     [38;5;66;03m# If there was no explicit definition, cls.set is inherited from[39;00m
[1;32m    143[0m     [38;5;66;03m# the hierarchy of auto-generated set methods, which hold the[39;00m
[1;32m    144[0m     [38;5;66;03m# flag _autogenerated_signature.[39;00m
[1;32m    145[0m     [38;5;28;01mreturn[39;00m
[0;32m--> 147[0m [38;5;28mcls[39m[38;5;241m.[39mset [38;5;241m=[39m [38;5;28;01mlambda[39;00m [38;5;28mself[39m, [38;5;241m*[39m[38;5;241m*[39mkwargs: [43mArtist[49m[38;5;241;43m.[39;49m[43mset[49m[43m([49m[38;5;28;43mself[39;49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m
[1;32m    148[0m [38;5;28mcls[39m[38;5;241m.[39mset[38;5;241m.[39m[38;5;18m__name__[39m [38;5;241m=[39m [38;5;124m"[39m[38;5;124mset[39m[38;5;124m"[39m
[1;32m    149[0m [38;5;28mcls[39m[38;5;241m.[39mset[38;5;241m.[39m[38;5;18m__qualname__[39m [38;5;241m=[39m [38;5;124mf[39m[38;5;124m"[39m[38;5;132;01m{[39;00m[38;5;28mcls[39m[38;5;241m.[39m[38;5;18m__qualname__[39m[38;5;132;01m}[39;00m[38;5;124m.set[39m[38;5;124m"[39m

File [0;32m/usr/share/miniconda3/envs/computo/lib/python3.9/site-packages/matplotlib/artist.py:1227[0m, in [0;36mArtist.set[0;34m(self, **kwargs)[0m
[1;32m   1223[0m [38;5;28;01mdef[39;00m [38;5;21mset[39m([38;5;28mself[39m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m   1224[0m     [38;5;66;03m# docstring and signature are auto-generated via[39;00m
[1;32m   1225[0m     [38;5;66;03m# Artist._update_set_signature_and_docstring() at the end of the[39;00m
[1;32m   1226[0m     [38;5;66;03m# module.[39;00m
[0;32m-> 1227[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_internal_update[49m[43m([49m[43mcbook[49m[38;5;241;43m.[39;49m[43mnormalize_kwargs[49m[43m([49m[43mkwargs[49m[43m,[49m[43m [49m[38;5;28;43mself[39;49m[43m)[49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/computo/lib/python3.9/site-packages/matplotlib/artist.py:1219[0m, in [0;36mArtist._internal_update[0;34m(self, kwargs)[0m
[1;32m   1212[0m [38;5;28;01mdef[39;00m [38;5;21m_internal_update[39m([38;5;28mself[39m, kwargs):
[1;32m   1213[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m   1214[0m [38;5;124;03m    Update artist properties without prenormalizing them, but generating[39;00m
[1;32m   1215[0m [38;5;124;03m    errors as if calling `set`.[39;00m
[1;32m   1216[0m 
[1;32m   1217[0m [38;5;124;03m    The lack of prenormalization is to maintain backcompatibility.[39;00m
[1;32m   1218[0m [38;5;124;03m    """[39;00m
[0;32m-> 1219[0m     [38;5;28;01mreturn[39;00m [38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_update_props[49m[43m([49m
[1;32m   1220[0m [43m        [49m[43mkwargs[49m[43m,[49m[43m [49m[38;5;124;43m"[39;49m[38;5;132;43;01m{cls.__name__}[39;49;00m[38;5;124;43m.set() got an unexpected keyword argument [39;49m[38;5;124;43m"[39;49m
[1;32m   1221[0m [43m        [49m[38;5;124;43m"[39;49m[38;5;132;43;01m{prop_name!r}[39;49;00m[38;5;124;43m"[39;49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/computo/lib/python3.9/site-packages/matplotlib/artist.py:1193[0m, in [0;36mArtist._update_props[0;34m(self, props, errfmt)[0m
[1;32m   1191[0m             func [38;5;241m=[39m [38;5;28mgetattr[39m([38;5;28mself[39m, [38;5;124mf[39m[38;5;124m"[39m[38;5;124mset_[39m[38;5;132;01m{[39;00mk[38;5;132;01m}[39;00m[38;5;124m"[39m, [38;5;28;01mNone[39;00m)
[1;32m   1192[0m             [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m [38;5;28mcallable[39m(func):
[0;32m-> 1193[0m                 [38;5;28;01mraise[39;00m [38;5;167;01mAttributeError[39;00m(
[1;32m   1194[0m                     errfmt[38;5;241m.[39mformat([38;5;28mcls[39m[38;5;241m=[39m[38;5;28mtype[39m([38;5;28mself[39m), prop_name[38;5;241m=[39mk))
[1;32m   1195[0m             ret[38;5;241m.[39mappend(func(v))
[1;32m   1196[0m [38;5;28;01mif[39;00m ret:

[0;31mAttributeError[0m: Axes.set() got an unexpected keyword argument 'fontdict'

